
name: MyWorkflow

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:
  inputs:
  num-octocats:
    description: 'Number of Octocats'
    required: false
    default: '1'
  octocat-eye-color:
    description: 'Eye color of the Octocats'
    required: true

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - run: python programs/fprogram.py 30 50

      - name: success message
        run: echo program executed successfully on ubuntu-latest!!
  job2:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - run: python programs/fprogram.py 10 20

      - name: success message
        run: Write-Output "program executed successfully on windows-latest!!"